salesforceCredentials:
  loginUrl: https://login.salesforce.com
  clientId: 3MVG9TSaZ8P6zP1o1A7P_A_jpGGdzO3mLKxAQ0jAEqMOqLj6FciCOe1jME9rCY_yxFAgHDKSZj4CaSuEhIogK
  clientSecret: 817149208465114697
  grantService: /services/oauth2/token?grant_type=password
  username: jesus-salesforce-java-00@gmail.com
  password: lorkytest02ceQJPP7jsn7ovnDJhuOW02v1A
  restUrl: https://eu8.salesforce.com/services/apexrest